### ISSUE TITLE
[Issue: Netikslumas kitoje vietoje (BS-2020) šablonas]: vetą → vietą (praleista raidė)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#103]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** Issue: Netikslumas kitoje vietoje (BS-2020) šablonas
3. **Bylos pavadinimas ar nuoroda (URL):** https://github.com/mokymai/taisymai--bs-2020/issues/new?assignees=&labels=BS-2020&template=bs-2020--05-pranesimas-apie-netiksluma.md&title=%5Bvieta%5D%3A+netikslumas+%E2%86%92+taisymas+%28netikslumo+esm%C4%97%29
4. **Glaustai aprašykite netikslumą:**  praleista raidė
 
5. **Nukopijuokite visą sakinį su netikslumu:** Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vetą ir esmę.

6. **Netikslumo tekstas:** galima identifikuoti problemos vetą ir esmę.
7. **Siūlomas taisymo tekstas:** galima identifikuoti problemos vietą ir esmę.
8. **Ekrano nuotrauka („Screenshot“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/60814335/82841730-cd734280-9edf-11ea-9b04-70325df094f8.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
👍
