### ISSUE TITLE
teorija-2020:  ir su kitos jomis → ir kitos su jomis (žodžių tvarka)

### ISSUE THREAD

**Issue by ruta-kiseliunaite** [mokymai/taisymai--bs-2020#122]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/ht-padetis.html
4. **Glaustai aprašykite netikslumą:**  netinkama žodžių tvarka 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** medianos ir su kitos jomis  
6. **Netikslumo tekstas:**  su kitos jomis 
7. **Siūlomas taisymo tekstas:** kitos su jomis
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

![image](https://user-images.githubusercontent.com/60814481/83413287-444e9500-a424-11ea-9247-c48847e34408.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/83493331-49abee00-a4bd-11ea-93ae-fa680850991e.png)
x reikia sudėti be tarpų, kaip rodoma pavyzdyje. t.y., `[x]`, o ne `[x ]` ar `[ x]`.
