### ISSUE TITLE
Papildomi balai (2020-06-01)

### ISSUE THREAD

**Issue by NojusMukauskas** [mokymai/taisymai--bs-2020#123]
1. **Genetika, II kursas** Biostatistika (BS-2020)
2. **Data:** 2020-06-01
3. **Surinkau 11/11 t07**

**Comment by GegznaV** [comment]
Kartojasi: #125

**Comment by Agne-B** [comment]
@GegznaV bet čia neturi nieko bendro su #125 čia dėl T07 testo
![paveikslas](https://user-images.githubusercontent.com/60814335/83440236-40833880-a44d-11ea-8c76-9c3ab5f38b37.png)

**Comment by NojusMukauskas** [comment]
Aš pamaniau, kad reikia į šią svetainę sukelti viską, už ką buvo gauti papildomi balai. Turbūt nereikėjo ;/

**Comment by GegznaV** [comment]
> 
> 
> @GegznaV bet čia neturi nieko bendro su #125 čia dėl T07 testo
> ![paveikslas](https://user-images.githubusercontent.com/60814335/83440236-40833880-a44d-11ea-8c76-9c3ab5f38b37.png)

@Agne-B, šitie bus įskaityti atskirai per _Emokymai_, o ne _GitHub_

**Comment by GegznaV** [comment]
Vienaip ar kitaip, šių balų nepatvirtinau.
