### ISSUE TITLE
BS-2020: pupų fenotipiniai požymiai → žirnių sėklų fenotipiniai požymiai (formuluotė)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#14]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** Įskaitinio darbo U06 „Pasikliautinieji intervalai“  trečio uždavinio sąlyga.
3. **Bylos pavadinimas ar nuoroda (URL):** Uzduotys BS-2020-U06-PI (2020-03-20)
4. **Glaustai aprašykite netikslumą:**  Netiksliai suformuluota uždavinio sąlyga (iš biologinės pusės).
 
5. **Nukopijuokite visą sakinį su netikslumu:** *Duoti duomenys, kuriuose iš visiškai atsitiktinai sudarytos pupų imties vertinami fenotipiniai požymiai (spalva – žalia ar geltona – bei paviršiaus lygumas – raukšlėtas ar lygus).*

6. **Netikslumo tekstas:** Pupų fenotipiniai požymiai
7. **Siūlomas taisymo tekstas:** Pupų *sėklų* fenotipiniai požymiai. Pati pupa yra **augalas** (lietuvių kalbos žodyne terminas "pupa" apibrėžiamas kaip " *kultūrinis ankštinis augalas (Vicia faba)*"). Augalas paprastai nėra nei geltonas, nei lygus, nei raukšlėtas.
8. **Ekrano nuotrauka („Screenshot“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/60814335/77480607-ae4a2d00-6e2a-11ea-9a5f-39debc219d2a.png)
P.S. klausimas kokia augalų rūšis buvo naudota eksperimente? Kaip statistikoje svarbu įvardinti naudotus metodus, taip biologiniuose straipsniuose svarbu paminėti organizmų rūšis (idealiausiu atveju su lotyniškais pavadinimais) 
P.S.S. Pastebėjimas, kad klasikiniuose Mendelio eksperimentuose su sėklų  fenotipais ir genotipais buvo naudojamas Sėjamasis žirnis (angl. Pea plant, lot. *Pisum sativum* L.). Uždavinio sąlyga priminė būtent šį eksperimentą, bet jeigu klystu, tai neabejoju, kad panašus eksperimentas galėjo būti atliktas ir su pupomis.

**Comment by GegznaV** [comment]
> Netiksliai suformuluota uždavinio sąlyga (iš biologinės pusės).

Sutinku dėl šito. Įprastai pats prie tokių dalykų kabinėjuosi.

> buvo naudojamas Sėjamasis žirnis

Turėjo būti žirnis. Nebepamenu, kodėl parašiau "pupos". Gal todėl, kad turėsime kitą uždavinį, kur žirniai auginami terpėje su auksinu. O gal todėl, kad duomenys yra sugeneruoti.

Ši užduotis jau paskelbta, tad nebetaisysiu. Bet jūsų pastabos labai geros ir į jas atsižvelgsiu darydamas kitus uždavinius.
