### ISSUE TITLE
teorija-2020: F – dešinioji asimetrija -> kairioji asimetrija, G – kairioji asimetrija -> dešinioji asimetrija

### ISSUE THREAD

**Issue by Dovydas777** [mokymai/taisymai--bs-2020#146]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/ht-normalumas.html
4. **Glaustai aprašykite netikslumą:**  
 fakto klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  E – dvi viršūnės, F – dešinioji asimetrija, G – kairioji asimetrija, H – dvi galimo
6. **Netikslumo tekstas:** F – dešinioji asimetrija, G – kairioji asimetrija
7. **Siūlomas taisymo tekstas:** F – kairioji asimetrija, G – dešinioji asimetrija
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![paveikslas](https://user-images.githubusercontent.com/64483179/83539175-6832d900-a4ff-11ea-98fc-308805696191.png)

Patvirtinkite pažymėdami [x]: 

- [ x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x ] Formą užpildžiau tinkamai.

**Comment by Agne-B** [comment]
@Dovydas777 čia klaidos nėra, bet truputį iš pirmo žvilgsnio klaidinantis grafikas. Tam, kad man lengviau būtų suprasti, aš viską paverčiau ant šono (kad reikšmės būtų x ašyje) ir padariau veidrodinį atspindį (kad reikšmės būtų nuo mažiausios iki didžiausios).
![paveikslas](https://user-images.githubusercontent.com/60814335/83542201-4dfafa00-a503-11ea-8dda-29ab2a9487e0.png)

**Comment by Dovydas777** [comment]
Dėkui! :)
