### ISSUE TITLE
teorija-2020: miegama ilgiau, nei -> miegama ilgiau nei 

### ISSUE THREAD

**Issue by Dovydas777** [mokymai/taisymai--bs-2020#151]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/ht-padetis.html
4. **Glaustai aprašykite netikslumą:**  nereikia kablelio prieš nei
 skyrybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  ar tikrai vartojant vaisto miegama ilgiau, nei nevartojant?
6. **Netikslumo tekstas:** ilgiau, nei
7. **Siūlomas taisymo tekstas:** ilgiau nei
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/64483179/83542836-31ab8d00-a504-11ea-8f42-b6dd5b8c242b.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
http://www.vlkk.lt/konsultacijos/4920-negu-nei-nekaip-negu-kaip-palyginimai
