### ISSUE TITLE
teorija-2020: ,,grupes, bus kalbama ir šiame, o kai turime kelias grupes – kitame'' -> ,,grupes, bus kalbama šiame, o kai turime kelias grupes – kitame'' 

### ISSUE THREAD

**Issue by Dovydas777** [mokymai/taisymai--bs-2020#153]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/ht-padetis.html
4. **Glaustai aprašykite netikslumą:**  
 rašyba/gramatika
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  grupes, bus kalbama ir šiame, o kai turime kelias grupes – kitame
6. **Netikslumo tekstas:** bus kalbama ir šiame
7. **Siūlomas taisymo tekstas:** bus kalbama šiame arba  kai turime 1 ar 2 duomenų grupes, ir bus kalbama šiame
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/64483179/83543536-37ee3900-a505-11ea-8787-e697c3924f37.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
> "[...] bus kalbama ir šiame [...]" (ir kitame)

**Comment by GegznaV** [comment]
kelios grupės reiškia "2 ar daugiau"
