### ISSUE TITLE
P15-6 (v1.0) sk.45: netikslumas → taisymas (skaidrės)

### ISSUE THREAD

**Issue by IgneKuk** [mokymai/taisymai--bs-2020#155]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P16-5 v1.0 
4. **Skaidrės numeris:** 45
5. **Glaustai aprašykite netikslumą:** neteisinga parašyta.

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** "neformalus paaiškiinimas   
7. **Netikslumo tekstas:** paaiškiinimas
8. **Siūlomas taisymo tekstas:** paaiškinimas
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/60871934/83543663-6bc95e80-a505-11ea-9692-b48eeca3c213.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by Agne-B** [comment]
Kartojasi: #154
