### ISSUE TITLE
P15-6 (v1.0) sk.90: tie → ties(skaidrės)

### ISSUE THREAD

**Issue by IgneKuk** [mokymai/taisymai--bs-2020#157]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P15-6 v1.0
4. **Skaidrės numeris:**90 
5. **Glaustai aprašykite netikslumą:** tie

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  "tie"
7. **Netikslumo tekstas:** ties
8. **Siūlomas taisymo tekstas:** ...
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

![image](https://user-images.githubusercontent.com/60871934/83544602-d62ece80-a506-11ea-8e63-10b0ddfc9576.png)

Patvirtinkite pažymėdami [x]:

- [ x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by Agne-B** [comment]
Kartojasi: #156
