### ISSUE TITLE
P15-6 (v1.0) sk.59: "bendros masės." → "bendros masės". (skyryba)

### ISSUE THREAD

**Issue by Aiste-P** [mokymai/taisymai--bs-2020#159]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P16 v1.0 
4. **Skaidrės numeris:** 59 
5. **Glaustai aprašykite netikslumą:** Taškas sakinio gale visada dedamas po kabučių ar skliaustelių, ne prieš juos.

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** " nuo „bendros masės.“"
 
7. **Netikslumo tekstas:** "Išskirtys yra taškai, išsiskiriantys nuo „bendros masės.“"
8. **Siūlomas taisymo tekstas:** "Išskirtys yra taškai, išsiskiriantys nuo „bendros masės**".**"
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Screenshot_9](https://user-images.githubusercontent.com/62069143/83545853-7b967200-a508-11ea-8d91-b5b3a24445af.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by apoptoze** [comment]
Skaidrės P15-6, ne P16.

**Comment by GegznaV** [comment]
Šioje vietoje skirtingi šaltiniai teigia skirtingai. Pvz., mano gramatikos taisymo įrankiai siūlo tašką visada rašyti kabučių viduje.
