### ISSUE TITLE
P15-6 (v1.0) sk.53: Svarbiai → svarbiau (klaida žodyje)

### ISSUE THREAD

**Issue by Aiste-P** [mokymai/taisymai--bs-2020#161]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P16 v1.0 
4. **Skaidrės numeris:** 53 
5. **Glaustai aprašykite netikslumą:** Klaida žodyje "svarbiau"

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** " Svarbiai, kad liekamosios " 
7. **Netikslumo tekstas:** "pageidautina, bet nebūtina. Svarbiai, kad liekamosios paklaidos būtų normaliosios"
8. **Siūlomas taisymo tekstas:** "pageidautina, bet nebūtina. **Svarbiau**, kad liekamosios paklaidos būtų normaliosios"
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![Screenshot_10](https://user-images.githubusercontent.com/62069143/83546295-1f801d80-a509-11ea-98c5-f1bd46ec8ce5.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kartojasi #143
