### ISSUE TITLE
Paveikslas 3.3 žodis 'Šaltinis' pakartotas 2 kartus

### ISSUE THREAD

**Issue by Dov-Pra** [mokymai/taisymai--bs-2020#163]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/tyrimu-planavimas.html#tyrimas-ir-eksperimentas
4. **Glaustai aprašykite netikslumą:**  žodis 'šaltinis' kartojasi 2 kartus.
 pakartota 2 kartus
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**Tikslumas ir glaudumas atvaizduoti kaip rezultatus apibendrinančio skirstinio savybės. Šaltinis: Šaltinis: simple.wikipedia.org.
6. **Netikslumo tekstas:** Šaltinis: Šaltinis:
7. **Siūlomas taisymo tekstas:** Šaltinis: 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/61143766/83547797-6a9b3000-a50b-11ea-8ab6-97603d862a9d.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
žymėti reikia `[x]`, o ne `[ x]` ar `[x ]`
