### ISSUE TITLE
P04-2(v1.0) sk.116: padalintą → padalytą (gramatikos klaida)

### ISSUE THREAD

**Issue by IgneKuk** [mokymai/taisymai--bs-2020#170]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P.04-2 v1.0 
4. **Skaidrės numeris:** 116 
5. **Glaustai aprašykite netikslumą:** gramatikos klaida, padalyti-priešdėlis "yt", o ne "int".

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** "padalintą iš n-1"
7. **Netikslumo tekstas:** padalintą
8. **Siūlomas taisymo tekstas:** padalytą
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/60871934/83551684-58bc8b80-a511-11ea-8f65-cfd32be07708.png)
![image](https://user-images.githubusercontent.com/60871934/83551734-696d0180-a511-11ea-9efc-c819877d008a.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
http://www.vlkk.lt/konsultacijos/4607-dalyti-dalinti
