### ISSUE TITLE
P06-1 (v1.0) sk.95: sėkminga ar teigiama → sėkmingą ar teigimą (nesuderinti linksniai)

### ISSUE THREAD

**Issue by IgneKuk** [mokymai/taisymai--bs-2020#175]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P06-1 v1.0 
4. **Skaidrės numeris:** 95 
5. **Glaustai aprašykite netikslumą:** nesuderinti linksniai, atsako į klausimą "suprantame kaip ką?"- galininko linksnis

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** "ką suprantame kaip teisinga ar tinkama" 
7. **Netikslumo tekstas:** teisinga ar tinkama
8. **Siūlomas taisymo tekstas:** teisingą ar tinkamą
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

![image](https://user-images.githubusercontent.com/60871934/83557137-cd93c380-a519-11ea-9082-75c410a01a57.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Bevardė giminė lietuvių kalboje nelinksniuojama. (Bevardė, nes "tai sėkminga").
