### ISSUE TITLE
P15-6(v1.0) sk._: darydami → daryti (netinkamas linksnis)

### ISSUE THREAD

**Issue by ruta-kiseliunaite** [mokymai/taisymai--bs-2020#179]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P15v6 (paprastoji tiesine regresija) 
4. **Skaidrės numeris:** 35 
5. **Glaustai aprašykite netikslumą:** netinkamas linksnis

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Pagal regresijos lygtį prognozes darydami korektiška tik
tada, 
7. **Netikslumo tekstas:** darydami
8. **Siūlomas taisymo tekstas:** daryti
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/60814481/83561374-6299bb00-a520-11ea-9b12-94cab6b51ae9.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kartojasi #150
