### ISSUE TITLE
P15-1(v2.0) sk.10: trūksta kablelio (skaidrės)

### ISSUE THREAD

**Issue by IgneKuk** [mokymai/taisymai--bs-2020#186]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P15-01 v2.0. 
4. **Skaidrės numeris:** 10 
5. **Glaustai aprašykite netikslumą:** skyrybos klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** "skaičiumi tarkime 0,05" 
7. **Netikslumo tekstas:** "skaičiumi tarkime"
8. **Siūlomas taisymo tekstas:"skaičiumi, tarkime 0,05"
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/60871934/83596452-4f610c80-a56d-11ea-8b13-d7e074f08f62.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v2.1
