### ISSUE TITLE
BS-2020: netikslumas → taisymas (rašybos ir vertimo klaidos)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#2]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/tyrimu-planavimas.html#tyrimas-ir-eksperimentas
4. **Glaustai aprašykite netikslumą:** tiek prie "paprastoji atsitiktinė grąžintinė imtis", tiek prie "paprastoji atsitiktinė negrąžintinė imtis" angliškų pavadinimų parašyta tas pats "simple random sampling with replacement". Prie lizdinės imties angliško pavadinimo parašyta "rendom".

5. **Nukopijuokite visą sakinį su netikslumu:** įdėta nuotrauka su pažymėtomis netikslumo vietomis

6. **Netikslumo tekstas:** lizdinė imtis (angl. cluster rendom sampling), paprastoji atsitiktinė negrąžintinė imtis (angl. simple random sampling with replacement)
7. **Siūlomas taisymo tekstas:** lizdinė imtis (angl. cluster **random** sampling), paprastoji atsitiktinė negrąžintinė imtis (angl. simple random sampling **without** replacement)
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![](https://i.imgur.com/bzIQRLK.png)

**Comment by GegznaV** [comment]
Dėkui, tuoj įkelsiu pataisymus.
Dėl screen-shot'ų: padarius ekrano nuotrauką ar nukopijavus vaizdą užtenka GitHub pranešime užtenka paspausti Ctrl+V ir jūsų vaizdas bus įkeltas. Paveikslo atskirame serveryje saugoti nebūtina.
Taip pat galima naudoti tokį MarkDown kodą (jūsų atveju): `![](https://i.imgur.com/bzIQRLK.png)` (žymėjimas `![]()` yra skirtas įterpti paveikslus).

**Comment by GegznaV** [comment]
Atnaujinus puslapį klaidos turėtų nebebūti.
