### ISSUE TITLE
BS-2020: turime GA → turime imtį (??)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#28]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** [BS-2020] P12 video medžiagoje
3. **Bylos pavadinimas ar nuoroda (URL):** https://youtu.be/oLPlj3sJUCM?t=71 (nuorodoje iš karto pažymėtas laikas)
4. **Glaustai aprašykite netikslumą:**  ??
 
5. **Nukopijuokite visą sakinį su netikslumu:** "Ką mes turim imtį ar generalinę aibę? Tai aišku, kad jeigu yra tik va tiek, kiek mes čia suskaičiuotumėm, latvių ir estų, tai nėra visi estai ir nėra visi latviai. Šičia mes aiškiai turim generalinę aibę." (iš video)

6. **Netikslumo tekstas:** Šičia mes aiškiai turim generalinę aibę.
7. **Siūlomas taisymo tekstas:** Šičia mes aiškiai turim imtį.
8. **Ekrano nuotrauka („Screenshot“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/60814335/79669254-f1e24d80-81c2-11ea-883c-b72d4f10b373.png)

P.S. nebent aš kažką labai ne taip suprantu.

**Comment by GegznaV** [comment]
Akivaizdi klaida. Turi būti **Imtis**
