### ISSUE TITLE
BS-2020: duomenys paimti iš dažnių lentelės (ne ta dažnių lentelė?)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#42]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** BS-2020--HT--technine-dalis, 7.1.1 Kategoriniai kintamieji
3. **Bylos pavadinimas ar nuoroda (URL):** https://emokymai.vu.lt/mod/resource/view.php?id=137066
4. **Glaustai aprašykite netikslumą:**  ...
 
5. **Nukopijuokite visą sakinį su netikslumu:** ...

6. **Netikslumo tekstas:** binom.test(x = 40, n = 40 + 24, p = 0.5)
7. **Siūlomas taisymo tekstas:** binom.test(x = 35, n = 35 + 29, p = 0.5)
8. **Ekrano nuotrauka („Screenshot“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/60814335/80912776-0f2d2500-8d48-11ea-85dc-762d32db80ac.png)

**Comment by GegznaV** [comment]
Neatitikimas dėl pakeisto `set.seed()` generuojant duomenis. Jei i6bandytumėte kitą, gautimėte kitokį rezultatą.

Turbūt čia geriausia daryti kitokius pakeitimus:

``` r
set.seed(20)
n <- 64
vienas_kat <- tibble::tibble(
  lytis  = sample(factor(c("Moteris", "Vyras")), size = n, replace = TRUE)
)

(dazn_lent <- with(vienas_kat, table(lytis)))
#> lytis
#> Moteris   Vyras 
#>      35      29

c(x = dazn_lent[1])
#> x.Moteris 
#>        35
c(n = sum(dazn_lent))
#>  n 
#> 64

binom.test(x = dazn_lent[1], n = sum(dazn_lent), p = 0.5)
#> 
#>  Exact binomial test
#> 
#> data:  dazn_lent[1] and sum(dazn_lent)
#> number of successes = 35, number of trials = 64, p-value = 0.5323
#> alternative hypothesis: true probability of success is not equal to 0.5
#> 95 percent confidence interval:
#>  0.4174763 0.6717929
#> sample estimates:
#> probability of success 
#>               0.546875
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by GegznaV** [comment]
Taip neliks dviprasmybės pasikeitus duomenims.

**Comment by GegznaV** [comment]
Jei aktualu, įkelta nauja redakcija su aukščiau pateiktomis pastabomis.
