### ISSUE TITLE
[?]: dėl vadovėlių

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#43]
**Klausimas:**  
Šiek tiek yra kažkokių neatitikimų dėl vadovėlių leidimų. Jūs rugsėjo mėnesį nurodėte 2000 ir 2002 metų leidimus,
![paveikslas](https://user-images.githubusercontent.com/60814335/80917311-a012f900-8d66-11ea-9e00-ff8fbaef9636.png)
kuomet mokymų svetainėje visur cituojami 2006 ir 2008 metų leidimai.
![paveikslas](https://user-images.githubusercontent.com/60814335/80917371-157ec980-8d67-11ea-8769-4e1183bc4b94.png)
vu.is sistemoje įkeltame kurso aprašyme vėl skiriasi I vadovėlio leidimo metai.
![paveikslas](https://user-images.githubusercontent.com/60814335/80917356-fed87280-8d66-11ea-9e1d-c68a7155cd43.png)
Suprantu, kad tikriausiai labai didelių skirtumų tarp skirtingų leidimų nėra, tačiau šiek tiek maišosi.
Taip pat pastebėjimas į kurį norėčiau atkreipti dėmesį, kad daugelis kolegų iš Saulėtekio ima vadovėlius iš MKIC, o MKIC vadovėlių fonde išduodami **2009 ir 2011** metų vadovėliai. Iki šiol labai daug skirtumų ar kažkokių problemų nebuvo, tačiau 2011 metų leidime nėra šitos pasirinkimų schemos (arba ji ne tame puslapyje).
![paveikslas](https://user-images.githubusercontent.com/60814335/80917585-968a9080-8d68-11ea-9f1c-145341d5eb2f.png)
Atsižvelgiant į dabartinę situaciją (nelabai yra galimybės nueiti ir pasikeisti vadovėlio leidimą), mano klausimas būtų, jeigu tai nėra prieš kokias nors autorines teises, ar galėtumėte kurs nors įkelti tą schemą?

**Comment by GegznaV** [comment]
Rudojoje svetainėje yra tie vadovėliai, kuriuos esu nusipirkęs. Apraše, matyt, dar liko leidimai nuo buvusių dėstytojų. Nemaniau, kad tie leidimai kažkuo skiriasi išskyrus tuo, kad leisti pakartotinai. Nors šito nesu sutikrinęs, tad nuomonė gali būti klaidinga.

Schema yra visiškai paskutiniame puslapyje vadovėlio II dalyje (kuriame yra aprašyti neparametriniai metodai bei ANOVA). Puslapyje net numerio nėra užrašyta. Tiesiog atsiskaičiavau, kuris turėtų būti.

Mokomaisiais tikslais tą schemą jums esu patekęs skaidrėse apie principus, kaip rinktis HT metodą. Schema išskaityta per 2 skaidres.

**Comment by GegznaV** [comment]
Gal tiksliau reiktų sakyti „lentelė“, o ne „schema“

**Comment by Agne-B** [comment]
Radau, ačiū labai.

**Comment by GegznaV** [comment]
Visgi ten p.271. Pataisiau svetainėje.
