### ISSUE TITLE
BS-2020: Svetainė: ?? → veikianti nuoroda

### ISSUE THREAD

**Issue by padraika** [mokymai/taisymai--bs-2020#5]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** Svetainė 
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/tyrimu-planavimas.html
4. **Glaustai aprašykite netikslumą:** Rašoma ??, nors panašu, jog turėtų būti pavadinimas ir veikianti nuoroda.

 
5. **Nukopijuokite visą sakinį su netikslumu:** Pavyzdžiai susiję su samplaika: klaidos nepagrįstai darant išvadas apie priežastinį ryšį (žr. skyriuje „?? [Sąsaja neparodo priežastingumo]“).

6. **Netikslumo tekstas:** „?? [Sąsaja neparodo priežastingumo]“)
7. **Siūlomas taisymo tekstas:** Reikėtų įdėti funkcionuojančią nuorodą.

8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="960" alt="Klaida2" src="https://user-images.githubusercontent.com/60842106/77003821-b6a3f300-6966-11ea-8d88-1e868ec46a68.png">

**Comment by GegznaV** [comment]
Tai žinomas dalykas. Nuoroda veiks, kai svetainėje atsiras nauji skyriai. Tai vienas iš paskutinių skyrių.

**Comment by GegznaV** [comment]
Tam, kad nekiltų tokių apgaulingų nesusipratimų, įkėliau visas likusias (nors ir iki galo neužbaigtas) kurso temas.

Dėkui, kad pranešėte.
