### ISSUE TITLE
BS-2020: pagrindnės, potai, paaiškinta paaiškinta (rašyba)

### ISSUE THREAD

**Issue by Agne-B** [mokymai/taisymai--bs-2020#50]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/teorija-2020/ht-anova-ir-analogai.html
4. **Glaustai aprašykite netikslumą:** ...

5. **Nukopijuokite visą sakinį su netikslumu:** 
Jei pagrindnės analizės rezultatas statistiškai reikšmingas (...)
Kiekvienai potai skaičiuojamas efekto dydis.

6. **Netikslumo tekstas:** pagrindnės, Kiekvienai potai 
7. **Siūlomas taisymo tekstas:** pagrindinės, Kiekvienai porai 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![paveikslas](https://user-images.githubusercontent.com/60814335/80924071-b1bcc680-8d8f-11ea-83fe-83c399b503a8.png)

**Comment by Agne-B** [comment]
Toje pačioje svetainėje (nebekursiu naujo issue)
**Netikslumo tekstas:** traktuojamas kaip nepriklausomu kintamuoju paaiškinta paaiškinta sklaidos dalis.
![paveikslas](https://user-images.githubusercontent.com/60814335/80924639-bafb6280-8d92-11ea-9843-0741086fa769.png)

**Comment by GegznaV** [comment]
@Agne-B, ar galėtumėte tuos netaisyklingai parašytus žodžius sudėti į pavadinimą, kad kolegos matytų ir be reikalo naujų **issues** neatidarinėtų? Pvz., "potai" kartojasi #54. Dabartinių **Issues** taisyti nereikia, nes jau pataisiau (uždarysiu turbūt rytoj). Kalbu apie naujus pranešimus.

**Comment by GegznaV** [comment]
@Agne-B, @Bernadeta-Al, labai dėkui už jūsų aktyvią pagalbą šiandien.

**Comment by GegznaV** [comment]
> Pvz., "potai" kartojasi #53. 
 turi būti #53
