### ISSUE TITLE
BS-2020: potai→ porai

### ISSUE THREAD

**Issue by Bernadeta-Al** [mokymai/taisymai--bs-2020#53]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** [Nuoroda](https://mokymai.github.io/teorija-2020/ht-anova-ir-analogai.html#ref-Cekanavicius2008)
4. **Glaustai aprašykite netikslumą:** ...

5. **Nukopijuokite visą sakinį su netikslumu:** ...

6. **Netikslumo tekstas:** Kiekvienai potai skaičiuojamas efekto dydis.
7. **Siūlomas taisymo tekstas:** Kiekvienai porai skaičiuojamas efekto dydis.
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="621" alt="bs10" src="https://user-images.githubusercontent.com/60813811/80925278-1596bd80-8d97-11ea-904f-a9d6b0f85154.png">

**Comment by GegznaV** [comment]
Atnaujinkite svetainę (Refresh, <kbd>F5</kbd>). Šita klaida jau buvo pataisyta.

Nuorodą geriau rašykite kaip tekstą, kuris baigiasi `.html`. Taip būtų patogiau. Taisau ne svetainę tiesiogiai, o jos *R Markdown* ruošinį.
