### ISSUE TITLE
P15-1--daugkartiniai-lyginimai (v2.0)

### ISSUE THREAD

**Issue by ruta-kiseliunaite** [mokymai/taisymai--bs-2020#70]
1. **2 kursas molekulinė biologija** Biostatistika (BS-2020)
2. skaidrės
3. BS-2020--P15-1--daugkartiniai-lyginimai [(v2.0)]
![Ekrano kopija (103)](https://user-images.githubusercontent.com/60814481/81656356-a0cf1d80-943f-11ea-92fb-0232109cb20d.png)
![Ekrano kopija (104)](https://user-images.githubusercontent.com/60814481/81656362-a2004a80-943f-11ea-9567-a502640d929d.png)

4. **Skaidrės numeris:** ... 
5. Rašybos klaidos
6.
13 skaidrė:
"Žingsninė procedūra, kur kiekvienai p reikšmei **pareinamas** atskiras reikšmingumo lygmuo"
pareinamas -> parenkamas
6 skaidrė:
Jei reikia atlikti daugkartinius **lyginamus**, naudojamas pakoreguotas (griežtesnis, mažesnis) reikšmingumo lygmuo (𝛼′).
lyginamus -> lyginimus
7. 
"atlikti daugkartinius lyginamus"
" reikšmei pareinamas atskiras reikšmingumo lygmuo"
8.
Žingsninė procedūra, kur kiekvienai p reikšmei parenkamas atskiras reikšmingumo lygmuo.
Jei reikia atlikti daugkartinius lyginimus, naudojamas pakoreguotas (griežtesnis, mažesnis) reikšmingumo lygmuo (𝛼′)
9. 
![Ekrano kopija (105)](https://user-images.githubusercontent.com/60814481/81656948-2783fa80-9440-11ea-80d9-f31aba93da67.png)
![Ekrano kopija (106)](https://user-images.githubusercontent.com/60814481/81656951-281c9100-9440-11ea-9834-b931da8caa2d.png)

...

**Comment by GegznaV** [comment]
Netikslumas    |   Pastaba
---                   |---
pareinamas     | OK
lyginamus       | OK

---

Dėstytojo skaidrės: 📙 `BS-2020--P15-1--ht--04-keliu-gr-lyginimas--v2.0.1.pptx`
