### ISSUE TITLE
P15-2--koreliacija (v1.0)  (rašybos klaidos) [9 sk.] kastais -> kartais; [6 sk.] vieno linijoje -> vienoje linijoje;toks pats -> toks pat; [3 sk.] būtinas kablelis : kintamąjį kintamąjį -> kintamąjį, kintamąjį

### ISSUE THREAD

**Issue by ruta-kiseliunaite** [mokymai/taisymai--bs-2020#71]
Skaidrėse BS-2020--P15-2--koreliacija (v1.0)  

- **Kursas** Biostatistika (BS-2020)
- skaidrės:  BS-2020--P15-2--koreliacija (v1.0)

![Ekrano kopija (109)](https://user-images.githubusercontent.com/60814481/81661566-f8bc5300-9444-11ea-834d-65fd68f9b353.png)
![Ekrano kopija (110)](https://user-images.githubusercontent.com/60814481/81661569-f9ed8000-9444-11ea-936d-4319e473b882.png)
![Ekrano kopija (107)](https://user-images.githubusercontent.com/60814481/81661609-0bcf2300-9445-11ea-987c-7afb8df8a5e4.png)
![Ekrano kopija (108)](https://user-images.githubusercontent.com/60814481/81661610-0c67b980-9445-11ea-9b3f-74fe9380e100.png)

Rašybos klaidos:

1)  **9 skaidrė:** Sąsajos tarp kintamųjų aprašymas.
"įprastai apvalinama iki 3sk **kastais** iki 4sk..."
kastais -> kartais. 
2) **6 skaidrė:** Kodėl vertinant koreliacijos koeficientą reikia ir grafiko?
"Keturios duomenų aibės, kurių koreliacijos koeficientas toks **pats**."
toks pats -> toks pat
3) **6skaidrė:** Koreliacijos stiprumas ir vaizdavimas grafiškai.
Klaida paveikslėlio pavadinime.
**Vieno linijoje** -> vienoje linijoje.
4) **3 skaidrė:** Pagal nominaliųjų kintamųjų skaičių galimi variantai
Skyrybos klaida:
"turime vieną atsitiktinį **kintamąjį kintamąjį** su k kategorijų"
taisymas:
"turime vieną atsitiktinį kintamąjį **,** kintamąjį su k kategorijų"

**Comment by GegznaV** [comment]
Netikslumas                                          | Komentaras
---                                                         | ---
[9 sk.] kastais -> kartais;                       | OK
[6 sk.] vieno linijoje -> vienoje linijoje; | OK
toks pats -> toks pat;                           | Nesuprantu, kodėl čia netikslumas
[3 sk.] būtinas kablelis : kintamąjį kintamąjį -> kintamąjį, kintamąjį | OK (išbrauktas papildomas žodis)

-------------------------------------------------------------------------  
Pastaba sau: 

- 📙 `BS-2020--P15-4--koreliacija-(v1.2.5).pptx` 
- 📙 `BS-2020--P15-2--04-proporcijos-v1.0.1.pptx`
