### ISSUE TITLE
P10: 11 skaidrėje žodis "parankama" → parenkama

### ISSUE THREAD

**Issue by apoptoze** [mokymai/taisymai--bs-2020#76]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Bylos pavadinimas ar nuoroda (URL):** P10--ht-02-klaidos (v1.0)
4. **Glaustai aprašykite netikslumą:** 11 skaidrėje neteisingai parašytas žodis "parenkama".
 
5. **Nukopijuokite visą sakinį su netikslumu:** "Tad šios klaidos tikimybė parankama prieš tyrimą"

6. **Netikslumo tekstas:** parankama
7. **Siūlomas taisymo tekstas:** parenkama
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/60874125/82030148-b42cf380-96a0-11ea-91cb-9e267bfe3ba4.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėstytojo skaidrės: 📙 `BS-2020--ht--02-ht-klaidos.pptx`
