### ISSUE TITLE
P11: 8 skaidrėje žodis "lema" → lemia

### ISSUE THREAD

**Issue by apoptoze** [mokymai/taisymai--bs-2020#77]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Bylos pavadinimas ar nuoroda (URL):** P11--ht-03--pasirinkimas (v2.0)
4. **Glaustai aprašykite netikslumą:** 8 skaidrėje neteisingai parašytas žodis "lemia".
 
5. **Nukopijuokite visą sakinį su netikslumu:** "Kokius skirtumus lema skirtingas sklaidos dydis ir efekto dydis."

6. **Netikslumo tekstas:** lema
7. **Siūlomas taisymo tekstas:** lemia
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/60874125/82030596-5351eb00-96a1-11ea-82f1-bf54c97ba086.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėstytojo skaidrės: 📙 `BS-2020--ht--03-kriteriju-pasirinkimas--v1.2.pptx`
