### ISSUE TITLE
P10: 7 skaidrėje žodis "variname" → vadiname

### ISSUE THREAD

**Issue by apoptoze** [mokymai/taisymai--bs-2020#78]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Bylos pavadinimas ar nuoroda (URL):** P10--ht-02-klaidos (v1.0)
4. **Glaustai aprašykite netikslumą:** 7 skaidrėje neteisingai parašytas žodis "vertiname".
 
5. **Nukopijuokite visą sakinį su netikslumu:** "Kriterijaus galia (1 − 𝛽) variname tikimybę atmesti antros rūšies klaidą."

6. **Netikslumo tekstas:** variname
7. **Siūlomas taisymo tekstas:** vertiname
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/60874125/82030961-d3785080-96a1-11ea-9b08-dbd8a2b6b141.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
"vadiname"

**Comment by GegznaV** [comment]
📙 `BS-2020--ht--02-ht-klaidos.pptx`
