### ISSUE TITLE
P15-6 skaidrės: 10 skaidrėje neteisingai užrašytas žodis "regresotius"→ "regresorius"

### ISSUE THREAD

**Issue by keiginte** [mokymai/taisymai--bs-2020#91]
**Kursas:** Biostatistika (BS-2020)
**Netikslumo vieta:** skaidrės P15-6
**Bylos pavadinimas ar nuoroda (URL):** https://emokymai.vu.lt/pluginfile.php/665890/mod_resource/content/1/BS-2020--P15-6--paprastoji-tiesine-regresija%20%28v1.0%29.pdf
**Glaustai aprašykite netikslumą:**  Duomenų lentelėje neteisingai parašytas žodis "regresotius", kuris turėtų būti "regresorius"
 
**Netikslumo tekstas:** regresotius
**Siūlomas taisymo tekstas:** regresorius
**Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![Capture](https://user-images.githubusercontent.com/60812877/82735842-70378f80-9d2d-11ea-9cca-6fa6af9efb67.JPG)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vetą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėstytojo skaidrės: :orange_book: `BS-2020--regresija-1-3-modelis.pptx`
